version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - cmake -S . -B build -DTRX_BUILD_DOCS=ON
      - cmake --build build --target docs

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
