coverage:
  status:
    project:
      default:
        paths:
          - "include/trx"
          - "src"
    patch:
      default:
        informational: true
        paths:
          - "include/trx"
          - "src"
