coverage:
  ignore:
    - "third_party"
    - "examples"
  status:
    project:
      default:
        paths:
          - "include/trx"
          - "src"
    patch:
      default:
        informational: true
        paths:
          - "include/trx"
          - "src"
